#! /usr/bin/env python
"""
These are helper classes for reading and working with files 
generated by TRiP and Virtuos.

   from pytrip import *


"""

__all__ = ['CtxCube', 'Vdx', 'GetDvh', 'DoseCube', 'Header']
__author__ = "Niels Bassler"
__version__ = "1.0"
__email__ = "bassler@phys.au.dk"

from hed import Header
from ctx2 import CtxCube
from dos2 import DosCube
from vdx2 import VdxCube
from get_dvh  import GetDvh
